# Generated by Django 4.2.2 on 2023-09-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_to_hire',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
