# Generated by Django 4.2.2 on 2023-09-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='topic',
            field=models.CharField(choices=[('commercial', 'commercial'), ('resedential', 'resedential')], default=0, max_length=100),
            preserve_default=False,
        ),
    ]
