# Generated by Django 4.2.2 on 2023-09-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0004_appointment_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_mail_me',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField(blank=True, max_length=1000, null=True)),
                ('topic', models.CharField(choices=[('HIRE_ME', 'HIRE ME'), ('CONTACT_ME', 'CONTACT ME'), ('COLLABORATION', 'COLLABORATION REQUEST')], default='CONTACT_ME', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
