# Generated by Django 4.2.2 on 2023-09-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning', '0005_record_mail_me'),
    ]

    operations = [
        migrations.CreateModel(
            name='SUBSCRIPTION',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
